### PR TITLE
Creating async overloads for extensions and create a count method extension

### PR DESCRIPTION
**Pull request by moxplod**

### CODE REVIEW

**Comment by MoonStorm** [comment]
Thanks. Will merge your work as soon as I get my local to a more stable state in preparation for the next release.

**Comment by MoonStorm** [comment]
Thanks for the effort. I've merged with the beta branch and released on nuget as 2.1 beta.

I added tests for all the async methods and found and fixed a bug where inserts were failing in the async method when an entity with no keys was used. Weird as the non-async dapper method was not behaving this way. 

Also I've changed the count async method and added a non-async count, similar to yours. I removed the insertion of the key columns in the COUNT as they don't offer any performance improvement and also the query would fail for an entity with no primary keys.

**Comment by moxplod** [comment]
If you removed keys from count - then you might want to put them back as overloads for the postgres versions. As there are known performance issues when you do something like count(*) vs count(ID).

**Comment by moxplod** [comment]
Is the 2.1 code out in some other git repository? Can i see it?

**Comment by moxplod** [comment]
nvm i see the beta branch.

**Comment by MoonStorm** [comment]
Alright. Will check for the number of keys prior to the inclusion. Thanks for the heads up.

**Comment by MoonStorm** [comment]
Always wanted to get to the bottom of this and here it is. 
```
 ANSI 92 spec, section 6.5, General Rules:
 a) If COUNT(*) is specified, then the result is the cardinality
          of T.

  b) Otherwise, let TX be the single-column table that is the
          result of applying the <value expression> to each row of T
          and eliminating null values. If one or more null values are
          eliminated, then a completion condition is raised: warning-
          null value eliminated in set function.
```
In other words, anything inside the COUNT will be evaluated and if is found to be NULL, the record will get discarded from the count, which in theory should be even worse than COUNT(*).

In this test however it makes no difference: http://www.sqlfiddle.com/#!15/47c21/4 , but you can see the effect of the last count, where one value is NULL in there, hence reporting a record less.

**Pull request closed without merging**
