### PR TITLE
Enhancing calculated column support for Mysql

### PR DESCRIPTION
**Pull request by CameronFiederer**
I updated the logic, and did my best to validate I didn't break anything. I did a small bit of refactoring, but if that's not welcome, (or perhaps I should be applying to the other sql flavors) I'm happy to undo it.

### CODE REVIEW

**Comment by CameronFiederer** [comment]
fixes #34

**Comment by MoonStorm** [comment]
It looks good. Thanks. I'll integrate the changes into the main branch, trigger a build and push a preview nuget package. I'll change the other db sql builders and add tests with this case by the time the release version of 2.4.0 goes live.

**Comment by CameronFiederer** [comment]
Hey, I can go ahead and place it in master, and adjust the other sql builders, at least postgres and mssql look like they don't need a fix, and sqlite can just use the same code. Not quite familiar with your testing patterns, so that might take me quite a bit longer to figure out, if you don't mind writing them

**Comment by MoonStorm** [comment]
Ok. Already merged your changes in ``master`` so you can continue working there. In the meantime I can work on some new tests.

**Pull request merged**
